version: "3"

services:

  ugc_etl:
    image: ugc_service
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - kafka_network
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2

  kafka-0:
    image: bitnami/kafka:3.5.1
    restart: unless-stopped
    container_name: kafka0container
    ports:
      - '10000:9094'
    networks:
      - kafka_network
    volumes:
      - "Kafka0:/bitnami/kafka"
    depends_on:
      - zookeeper

  kafka-1:
    image: bitnami/kafka:3.5.1
    restart: unless-stopped
    container_name: kafka1container
    ports:
      - '10001:9094'
    networks:
      - kafka_network
    volumes:
      - "Kafka1:/bitnami/kafka"
    depends_on:
      - zookeeper

  kafka-2:
    image: bitnami/kafka:3.5.1
    container_name: kafka2container
    restart: unless-stopped
    ports:
      - '10002:9094'
    networks:
      - kafka_network
    volumes:
      - "Kafka2:/bitnami/kafka"
    depends_on:
      - zookeeper

  KafkaWebUi:
    image: provectuslabs/kafka-ui:latest
    restart: always
    container_name: kafka_web_ui_container
    ports:
      - '8082:8080'
    networks:
      - kafka_network
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - kafka_network

  clickhouse-node1:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/node1:/etc/clickhouse-server
    networks:
      - kafka_network
    depends_on:
      - zookeeper

  clickhouse-node2:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse-node2
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ./data/node2:/etc/clickhouse-server
    networks:
      - kafka_network
    depends_on:
      - zookeeper

  clickhouse-node3:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse-node3
    ports:
      - "8125:8123"
      - "9002:9000"
    volumes:
      - ./data/node3:/etc/clickhouse-server
    networks:
      - kafka_network
    depends_on:
      - zookeeper

  clickhouse-node4:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse-node4
    ports:
      - "8126:8123"
      - "9003:9000"
    volumes:
      - ./data/node4:/etc/clickhouse-server
    networks:
      - kafka_network
    depends_on:
      - zookeeper

networks:
  kafka_network:
    driver: bridge

volumes:
  Kafka0:
    driver: local
  Kafka1:
    driver: local
  Kafka2:
    driver: local
  clickhouse-node1:
    driver: local
  clickhouse-node2:
    driver: local
  clickhouse-node3:
    driver: local
  clickhouse-node4:
    driver: local