version: '3'

services:
  
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - olap_network

  clickhouse-node1:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/node1:/etc/clickhouse-server
    depends_on:
      - zookeeper
    networks:
      - olap_network
  
  vertica-node1:
    image: jbfavre/vertica:latest
    container_name: vertica_container
    ports:
      - "5433:5433"
    networks:
      - olap_network


networks:
  olap_network:
    driver: bridge
